name: ${project.name}
description: ${project.description}
version: ${project.version}
main: ${main.class}
author: ${author}
api-version: 1.13
depend: [LuckPerms, CommandAPI]
softdepend: [PlaceholderAPI]
